---
# TODO Clone and add dotfiles repo

- name: Add dynamic dotfiles
  ansible.windows.win_template:
    src: '{{ item }}.j2'
    dest: "{{ user_profile }}\\{{ item }}"
  loop:
    - .gitconfig
    - .netrc
    - .npmrc
    - .tinypng
