---
- name: Check if dotfiles install script is already in-place
  stat:
    path: ~/.local/bin/install-dotfiles
  register: dotfiles_install_script

- name: Install the dotfiles with script
  shell:
    cmd: curl -sSL https://gitlab.com/megabyte-labs/dotfiles/-/raw/master/dotfiles/.local/bin/install-dotfiles > /tmp/install-dotfiles && bash /tmp/install-dotfiles
  when: not dotfiles_install_script.stat.exists
  args:
    executable: /bin/bash

- name: Add dynamic dotfiles
  template:
    src: '{{ item }}.j2'
    dest: '~/{{ item }}'
    owner: '{{ user.username | default(omit) }}'
    group: '{{ user.group | default(omit) }}'
    mode: 0600
  loop:
    - .gitconfig
    - .netrc
    - .npmrc
    - .tinypng
  when: include_pii_dotfiles | default(false)
